### ISSUE TITLE
Unable to access the configuration object : REST API failure, code : 503

### ISSUE THREAD

**Issue by benapetr** [ceph/ceph-iscsi#135]
Following this guide https://docs.ceph.com/docs/master/rbd/iscsi-target-cli/

I reached the point when I am supposed to use gwcli, but it just doesn't work:

```
TEST [root@ceph1 ceph-iscsi]# gwcli
Unable to access the configuration object : REST API failure, code : 503
GatewayError:
```

All services as required in manual are installed and running

```
TEST [root@ceph1 ceph-iscsi]# service rbd-target-gw status
Redirecting to /bin/systemctl status rbd-target-gw.service
● rbd-target-gw.service - Setup system to export rbd images through LIO
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-gw.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-08-30 15:41:49 CEST; 3min 47s ago
 Main PID: 25769 (rbd-target-gw)
   Memory: 22.1M
   CGroup: /system.slice/rbd-target-gw.service
           └─25769 /usr/bin/python /usr/bin/rbd-target-gw

Aug 30 15:41:49 ceph1.cz.nonprod systemd[1]: Started Setup system to export rbd im...O.
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: Integrated Prometheus export...d
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: * Serving Flask app "rbd-tar...)
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: * Environment: production
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: WARNING: Do not use the deve....
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: Use a production WSGI server....
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]: * Debug mode: off
Aug 30 15:41:49 ceph1.cz.nonprod rbd-target-gw[25769]:  * Running on http://[::]:92...)
Hint: Some lines were ellipsized, use -l to show in full.
TEST [root@ceph1 ceph-iscsi]#
TEST [root@ceph1 ceph-iscsi]# service rbd-target-api status
Redirecting to /bin/systemctl status rbd-target-api.service
● rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-08-30 15:37:52 CEST; 7min ago
 Main PID: 25421 (rbd-target-api)
   Memory: 45.1M
   CGroup: /system.slice/rbd-target-api.service
           └─25421 /usr/bin/python /usr/bin/rbd-target-api

Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: Processing osd blacklist en...e
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: No OSD blacklist entries found
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: Reading the configuration o...n
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: Configuration does not have...O
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: * Serving Flask app "rbd-ta...)
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: * Environment: production
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: WARNING: Do not use the dev....
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: Use a production WSGI serve....
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]: * Debug mode: off
Aug 30 15:37:53 ceph1.cz.nonprod rbd-target-api[25421]:  * Running on http://[::]:5...)
Hint: Some lines were ellipsized, use -l to show in full.
```

What is the problem?

**Comment by JKJameson** [comment]
Run gwcli with debug option: gwcli -d
Hopefully that sheds some more light on the issue.

**Comment by benapetr** [comment]
```
TEST [root@ceph1 ceph-iscsi]# gwcli -d
Adding ceph cluster 'ceph' to the UI
Fetching ceph osd information
Querying ceph for state information
Unable to access the configuration object : REST API failure, code : 503
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 4, in <module>
    __import__('pkg_resources').run_script('ceph-iscsi==3.2', 'gwcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.2-py2.7.egg/EGG-INFO/scripts/gwcli", line 194, in <module>

  File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.2-py2.7.egg/EGG-INFO/scripts/gwcli", line 105, in main

  File "build/bdist.linux-x86_64/egg/gwcli/gateway.py", line 82, in refresh
gwcli.utils.GatewayError
```

**Comment by dillaman** [comment]
What happens when you run the following (tweak for http(s), username, password, and port if needed):

curl --insecure --user admin:admin -X GET http://localhost:5000/api/config

**Comment by benapetr** [comment]
At some point it might be related to http_proxy and https_proxy variables I had to configure to download all the git repos and pypi dependencies, these lab machines are behind strong firewall unfortunatelly, so I can't access any internet resources without that proxy

```
TEST [root@ceph1 ceph-iscsi]# curl --insecure --user admin:admin -X GET http://localhost:5000/api/config
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The requested URL could not be retrieved</TITLE>
<STYLE type="text/css"><!--BODY{background-color:#ffffff;font-family:verdana,sans-serif}PRE{font-family:sans-serif}--></STYLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The requested URL could not be retrieved</H2>
<HR noshade size="1px">
<P>
While trying to retrieve the URL:
<A HREF="http://localhost:5000/api/config">http://localhost:5000/api/config</A>
<P>
The following error was encountered:
<UL>
<LI>
<STRONG>
Connection to 127.0.0.1 Failed
</STRONG>
</UL>

<P>
The system returned:
<PRE><I>    (111) Connection refused</I></PRE>

<P>
The remote host or network may be down.  Please try the request again.
<P>Your cache administrator is <A HREF="mailto:app@homecredit.net?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20app-proxy02.homecredit.net%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Fri,%2030%20Aug%202019%2014%3A01%3A37%20GMT%0D%0A%0D%0AClientIP%3A%2010.129.112.30%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fapi%2Fconfig%20HTTP%2F1.1%0AAuthorization%3A%20Basic%20YWRtaW46a29rb3QxMjM%3D%0D%0AUser-Agent%3A%20curl%2F7.29.0%0D%0AHost%3A%20localhost%3A5000%0D%0AAccept%3A%20*%2F*%0D%0AProxy-Connection%3A%20Keep-Alive%0D%0A%0D%0A%0D%0A">app@homecredit.net</A>.

<br>
<hr>
<div id="footer">
Generated Fri, 30 Aug 2019 14:01:37 GMT by app-proxy02.homecredit.net (squid/3.0.STABLE25)
</div>
</body></html>
```

I will try to get rid of that proxy vars

**Comment by benapetr** [comment]
now it looks much better, so it probably was fault on my side, just the error wasn't very clear to me (neither how to debug / investigate)
