### ISSUE TITLE
run rbd-target-api, "No module named gateway" error

### ISSUE THREAD

**Issue by soulmem** [ceph/ceph-iscsi#145]
[root@node3 ~]# rbd-target-api
Traceback (most recent call last):
  File "/usr/bin/rbd-target-api", line 5, in <module>
    pkg_resources.run_script('ceph-iscsi==3.2', 'rbd-target-api')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.2-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 38, in <module>

  File "/root/ceph-iscsi/build/scripts-2.7/gwcli.py", line 15, in <module>
    from gwcli.gateway import ISCSIRoot
ImportError: No module named gateway

**Comment by JKJameson** [comment]
You hit a bug. Please tell us what you did that caused the error so that it can be fixed.

You can fix your install by deleting your config and starting over.

rados -p rbd rm gateway.conf
systemctl restart rbd-target-api
systemctl restart rbd-target-gw

**Comment by mikechristie** [comment]
You seem to be mixing packages.

1. Are you trying to use the newer ceph-iscsi 3.X package?

Make sure you uninstall ceph-iscsi-cli/ceph-iscsi-config.

2. Are you trying to use the older ceph-iscsi-config/ceph-iscsi-cli packages?

Make sure you have ceph-iscsi uninstalled.


If you are not using rpm, then you should go into

/usr/lib/python2.7/site-packages/

and remove the .egg and/or dirs for those packages.

**Comment by soulmem** [comment]
The version of ceph is nautilus, and the version of tcmu-runner is 1.5.2.
  Yesterday, I reinstalled all the software of CEPH and iSCSI through ansible. Then I cloned the latest ceph-iscsi and installed it by “Python setup.py install”. This error nerver happened again.
