### ISSUE TITLE
Failed to start rbd-target-api

### ISSUE THREAD

**Issue by tanshaolong** [ceph/ceph-iscsi#157]
Hi,

I build a ceph iscsi gw service. I create an iscsi target by gwcli. I get error message “at least 2 gateways must exist before disk mapping operations are permitted” when I add ceph RBD image to the target disks. So, I set minimum_gateways to 1 at iscsi-gateway.cfg and restart rbd-target-api service, but it is failure. I remove the minimum_gateways option from iscsi-gateway.cfg. I can’t start the rbd-target-api service yet. Check messages, I can see “IndexError: list index out of range” exception for ceph iscsi.
Below is error from /var/log/messages
 ```
Dec  6 14:19:21 localhost systemd: Started Ceph iscsi target configuration API.
Dec  6 14:19:21 localhost systemd: Starting Ceph iscsi target configuration API...
Dec  6 14:19:22 localhost journal: Started the configuration object watcher
Dec  6 14:19:22 localhost journal: Checking for config object changes every 1s
Dec  6 14:19:22 localhost journal: Processing osd blacklist entries for this node
Dec  6 14:19:22 localhost journal: No OSD blacklist entries found
Dec  6 14:19:22 localhost journal: Reading the configuration object to update local LIO configuration
Dec  6 14:19:22 localhost journal: Processing Gateway configuration
Dec  6 14:19:22 localhost journal: Setting up iqn.2019-01.com.redhat.iscsi-gw:iscsi-igw
Dec  6 14:19:22 localhost rbd-target-api: Traceback (most recent call last):
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/bin/rbd-target-api", line 5, in <module>
Dec  6 14:19:22 localhost rbd-target-api: pkg_resources.run_script('ceph-iscsi==3.3', 'rbd-target-api')
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
Dec  6 14:19:22 localhost rbd-target-api: self.require(requires)[0].run_script(script_name, ns)
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
Dec  6 14:19:22 localhost rbd-target-api: exec_(script_code, namespace, namespace)
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
Dec  6 14:19:22 localhost rbd-target-api: exec("""exec code in globs, locs""")
Dec  6 14:19:22 localhost rbd-target-api: File "<string>", line 1, in <module>
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.3-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2939, in <module>
Dec  6 14:19:22 localhost rbd-target-api: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.3-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2854, in main
Dec  6 14:19:22 localhost rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 239, in define
Dec  6 14:19:22 localhost rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 212, in define_targets
Dec  6 14:19:22 localhost rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 169, in define_target
Dec  6 14:19:22 localhost rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/target.py", line 586, in manage
Dec  6 14:19:22 localhost rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/target.py", line 388, in load_config
Dec  6 14:19:22 localhost rbd-target-api: IndexError: list index out of range
Dec  6 14:19:22 localhost systemd: rbd-target-api.service: main process exited, code=exited, status=1/FAILURE
Dec  6 14:19:22 localhost systemd: Unit rbd-target-api.service entered failed state.
Dec  6 14:19:22 localhost systemd: rbd-target-api.service failed.
 ```
How to fix the issue and start rbd-target-api service?

Thanks
Ray

**Comment by mikechristie** [comment]
Did you get the service running?

I see your other issue:

https://github.com/ceph/ceph-iscsi/issues/158

and it mentions you are running the service there.

What was the issue here?

**Comment by tanshaolong** [comment]
Thanks @mikechristie 

I explian my test situation. 
Couple of days ago, I created my firstly ceph iscsi_gw service(at Centos 7.4), but I met the above issue. I didn’t want it blocked my other investigation for ceph iscsi. So, I create both new iscsi_gw services at both centos 7.5 machines. The both new gw services are running well except I mentioned issue for #158.

If you need the more information for the issue, please let me know. Thank you very much.

**Comment by mikechristie** [comment]
Going to close this, because we do not have the setup to replicate it on your setup and I cannot replicate it here.
