### ISSUE TITLE
gwcli fails to create gateway on ubuntu 20.04

### ISSUE THREAD

**Issue by hemna** [ceph/ceph-iscsi#193]
When running gwcli to create a gateway, gwcli dumps out with

```
/iscsi-target...ndev/gateways> create devstack-20-2 192.168.122.174 skipchecks=true
CMD: ../gateways/ create devstack-20-2 ['192.168.122.174'] nosync=False skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
Gateway creation successful
Adding gw to UI
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 194, in <module>
    main()
  File "/usr/bin/gwcli", line 125, in main
    shell.run_interactive()
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 900, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 729, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 843, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 818, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3/dist-packages/gwcli/gateway.py", line 868, in ui_command_create
    gateway_hostname = api.response.json()['data']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 885, in json
    encoding = guess_json_utf(self.content)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 871, in guess_json_utf
    nullcount = sample.count(_null)
TypeError: must be str, not bytes
```

targetcli seems happy with the gateway

```
root@devstack-20-2:~# targetcli
targetcli shell version 2.1.51
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:fbo ............................................................................................... [Storage Objects: 0]
  | o- user:qcow .............................................................................................. [Storage Objects: 0]
  | o- user:rbd ............................................................................................... [Storage Objects: 0]
  | o- user:zbc ............................................................................................... [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.1993-08.org.opendev:opendev ................................................................................... [TPGs: 1]
  |   o- tpg1 ............................................................................................... [no-gen-acls, no-auth]
  |     o- acls .......................................................................................................... [ACLs: 0]
  |     o- luns .......................................................................................................... [LUNs: 0]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 192.168.122.174:3260 ............................................................................................. [OK]
  o- loopback ......................................................................................................... [Targets: 0]
  o- vhost ............................................................................................................ [Targets: 0]
  o- xen-pvscsi ....................................................................................................... [Targets: 0]
```

Ceph info

```
root@devstack-20-2:~# ceph -s
  cluster:
    id:     a7392d03-1af3-4e98-bc95-890826111cd9
    health: HEALTH_WARN
            13 mgr modules have failed dependencies
            1 pool(s) do not have an application enabled
            1 pool(s) have no replicas configured

  services:
    mon: 1 daemons, quorum devstack-20-2 (age 15m)
    mgr: x(active, since 15m)
    osd: 1 osds: 1 up (since 15m), 1 in (since 15m)

  data:
    pools:   1 pools, 8 pgs
    objects: 1 objects, 1.6 KiB
    usage:   1.0 GiB used, 99 GiB / 100 GiB avail
    pgs:     8 active+clean

  io:
    client:   853 B/s rd, 0 op/s rd, 0 op/s wr

root@devstack-20-2:~# ceph --version
ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)

root@devstack-20-2:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by hemna** [comment]
[This is the /var/log/rbd-target-api log of the transaction.](http://paste.openstack.org/show/794473/)

**Comment by hemna** [comment]
It seems that the issue is caused by the /etc/ceph/iscsi-gateway.cfg 
api_host = localhost setting.

The api call was trying to go to http://devstack-20-2:5002/sysinfo/hostname, which failed with connection refused.  
I changed the api_host = 0.0.0.0 and the issue went away.  

It would be nice to get a better error message in this case.

**Comment by dillaman** [comment]
Thanks -- looks like that section of code doesn't check the response code for success like the others.

**Comment by xin3liang** [comment]
I hit the same problem on Ubuntu 20.04 too. Any ideas to fix it?

**Comment by kevin-zhaoshuai** [comment]
The version is ceph-iscsi 3.4.

**Comment by kevin-zhaoshuai** [comment]
@hemna Just FYI, https://review.opendev.org/#/c/735078/1/devstack/lib/ceph, I leave some comments here, this problem looks like wrong configuration with hostname/hostip

**Comment by xin3liang** [comment]
This issue can be reproduced when setting api_host to 'localhost' and creating an another hostname gateway in python3. Let the api_host as default value "::" or "0.0.0.0"can avoid this issue. 
Because when setting api_host to 'localhost', api_port doesn't listen on hostname's IP leads to this issue.
Related issue: https://github.com/psf/requests/issues/4879
