### ISSUE TITLE
ceph-iscsi on a single node?

### ISSUE THREAD

**Issue by hemna** [ceph/ceph-iscsi#195]
Hello,
  I am working on adding an openstack cinder driver that does ceph iscsi.  The problem I'm running into is that it looks like recent versions of ceph-iscsi complain that I don't have more than 1 gateway when trying to create clients.  Unfortunately, this isn't possible for me as I can't create a vm while standing up devstack, just to create a second ip address.  I should be able to use ceph-iscsi in non HA mode accepting the risk.  It used to work.

I have to create a working environment on a single node to get openstack devstack CI to work and test against my ceph iscsi driver.  Is there a workaround for asking the rbd-target-api to ignore this check for an HA gateway setup?

I have tried to create an aliased interface and targetcli seems to be happy with it, but gwcli won't allow me to create a gateway against it.

Here is how I created the aliased network interface
```
ip link add link ens3 name ens4 address 00:11:22:33:44:55 type macvlan
dhclient ens4

ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.174  netmask 255.255.255.0  broadcast 192.168.122.255
        inet6 fe80::5054:ff:fec4:3de7  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:c4:3d:e7  txqueuelen 1000  (Ethernet)
        RX packets 63408  bytes 5969336 (5.9 MB)
        RX errors 0  dropped 79  overruns 0  frame 0
        TX packets 38088  bytes 8564408 (8.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.40  netmask 255.255.255.0  broadcast 192.168.122.255
        inet6 fe80::211:22ff:fe33:4455  prefixlen 64  scopeid 0x20<link>
        ether 00:11:22:33:44:55  txqueuelen 1000  (Ethernet)
        RX packets 10  bytes 1393 (1.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2058  bytes 2539972 (2.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Then I added an /etc/hosts entry for 'test' pointing to 192.168.122.40

```
/iscsi-target...ndev/gateways> ls
o- gateways .................................................................................................. [Up: 1/1, Portals: 1]
  o- devstack-20-2 .......................................................................................... [192.168.122.174 (UP)]
/iscsi-target...ndev/gateways> create test 192.168.122.40 skipchecks=true
CMD: ../gateways/ create test ['192.168.122.40'] nosync=False skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
Gateway creation successful
Adding gw to UI
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 194, in <module>
    main()
  File "/usr/bin/gwcli", line 125, in main
    shell.run_interactive()
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 900, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 729, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 843, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 818, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3/dist-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3/dist-packages/gwcli/gateway.py", line 872, in ui_command_create
    Gateway(self, gateway_hostname, portal_config)
  File "/usr/lib/python3/dist-packages/gwcli/gateway.py", line 911, in __init__
    UINode.__init__(self, gateway_name, parent)
  File "/usr/lib/python3/dist-packages/gwcli/node.py", line 52, in __init__
    UIGroup.__init__(self, name, parent)
  File "/usr/lib/python3/dist-packages/gwcli/node.py", line 38, in __init__
    UICommon.__init__(self, name, parent, shell)
  File "/usr/lib/python3/dist-packages/gwcli/node.py", line 11, in __init__
    ConfigNode.__init__(self, name, parent, shell)
  File "/usr/lib/python3/dist-packages/configshell_fb/node.py", line 104, in __init__
    raise ValueError("Name '%s' already used by a sibling."
ValueError: Name 'devstack-20-2' already used by a sibling.
```

I manually tried to create the portal in targetcli thinking it would help make gwcli happy, but I get the same exception.

```
root@devstack-20-2:~# targetcli
/usr/local/lib/python3.8/dist-packages/rtslib_fb/root.py:174: UserWarning: Cannot set dbroot to /etc/target. Target drivers have already been registered.
  warn("Cannot set dbroot to {}. Target drivers have already been registered."
targetcli shell version 2.1.51
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/iscsi/iqn.19.../tpg1/portals> ls
o- portals ............................................................................................................ [Portals: 2]
  o- 192.168.122.174:3260 ..................................................................................................... [OK]
  o- 192.168.122.40:3260 ...................................................................................................... [OK]
```

**Comment by dillaman** [comment]
> I am working on adding an openstack cinder driver that does ceph iscsi.

Can you explain the use-case for using Ceph iSCSI in OpenStack?

**Comment by hemna** [comment]
The purpose of adding a ceph iscsi driver to cinder is to allow baremetal to boot from a ceph iscsi volume.   There are a lot of folks asking for this and I've spent the time to get the driver working along with a rest client that talks to rbd-target-api here:
https://github.com/hemna/rbd-iscsi-client
and here:
https://review.opendev.org/#/c/662829/13

One of the requirements for OpenStack Cinder volume drivers is to have active and running CI tests to ensure that the driver works.   The way to do this is to get the driver working in a single node devstack setup.   So, this setup is for devstack so I can run CI tests against the driver.  It's not a use case for real world deployments.  
This is an example CI run for normal ceph volume driver here:
https://zuul.opendev.org/t/openstack/build/6d9d8e01dbc94b919523490e486b84ee

**Comment by dillaman** [comment]
I think `ceph-iscsi` is going to need a lot more work before it could properly support that use-case. While you can just tweak the `minimum_gateways` setting down to 1 for your test environment, in a real-world deployment, you will want to essentially treat these as read-only LUNs without ALUA active optimized/non-optimized paths. In fact, you might want to just look into adding support for krbd + iblock directly to `ceph-iscsi` for this use-case and avoid the need for `tcmu-runner` and its expectations of proper ALUA setup and single active gateway per LUN.

[1] https://github.com/ceph/ceph-iscsi/blob/master/ceph_iscsi_config/gateway_setting.py#L184

**Comment by kevin-zhaoshuai** [comment]
@hemna Hi, I have tested the configuration with minimum_gateway to 1, and finally I can mount the disk from Ceph-iscsi with only 1 gateway available.
