### ISSUE TITLE
iSCSI Gateway does not survive machine reboot

### ISSUE THREAD

**Issue by phausman** [ceph/ceph-iscsi#222]
Ubuntu Focal 20.04, ceph-iscsi rev. 3.4-0ubuntu2

After restarting the machine `rbd-target-api' service fails to start with the following error in journalctl:

```
Nov 03 14:13:20 node03 rbd-target-api[2512]: Started the configuration object watcher
Nov 03 14:13:20 node03 rbd-target-api[2512]: Checking for config object changes every 1s
Nov 03 14:13:20 node03 rbd-target-api[2512]: Processing osd blacklist entries for this node
Nov 03 14:13:20 node03 rbd-target-api[2512]: Removing blacklisted entry for this host : 172.27.81.86:0/1336704704
Nov 03 14:13:21 node03 rbd-target-api[2512]: Traceback (most recent call last):
Nov 03 14:13:21 node03 rbd-target-api[2512]:   File "/usr/bin/rbd-target-api", line 2952, in <module>
Nov 03 14:13:21 node03 rbd-target-api[2512]:     main()
Nov 03 14:13:21 node03 rbd-target-api[2512]:   File "/usr/bin/rbd-target-api", line 2862, in main
Nov 03 14:13:21 node03 rbd-target-api[2512]:     osd_state_ok = ceph_gw.osd_blacklist_cleanup()
Nov 03 14:13:21 node03 rbd-target-api[2512]:   File "/usr/lib/python3/dist-packages/ceph_iscsi_config/gateway.py", line 110, in osd_blacklist_cleanup
Nov 03 14:13:21 node03 rbd-target-api[2512]:     rm_ok = self.ceph_rm_blacklist(blacklist_entry.split(' ')[0])
Nov 03 14:13:21 node03 rbd-target-api[2512]:   File "/usr/lib/python3/dist-packages/ceph_iscsi_config/gateway.py", line 46, in ceph_rm_blacklist
Nov 03 14:13:21 node03 rbd-target-api[2512]:     if ("un-blacklisting" in result) or ("isn't blacklisted" in result):
Nov 03 14:13:21 node03 rbd-target-api[2512]: TypeError: a bytes-like object is required, not 'str'
Nov 03 14:13:21 node03 systemd[1]: rbd-target-api.service: Main process exited, code=exited, status=1/FAILURE
```

Quick debugging revealed that the value of the `result` variable in /usr/lib/python3/dist-packages/ceph_iscsi_config/gateway.py, line 46 is actually a bytes-like object: b'un-blacklisting 172.27.81.86:0/4201287430\n'. That's why the check `if ("un-blacklisting" in result) or ("isn't blacklisted" in result)` fails.

Casting the 'result' to str fixes the problem.

**Comment by dillaman** [comment]
I'd recommend updating your `ceph-iscsi` package because I'm pretty sure this issue has been fixed for a while via #170
