### ISSUE TITLE
Upgrading to format 4 fails because config doesn't have "controls" entry

### ISSUE THREAD

**Issue by emmericp** [ceph/ceph-iscsi#61]
Trying to upgrade a test cluster to the 3.0 release and it fails here: https://github.com/ceph/ceph-iscsi/blob/3.0/ceph_iscsi_config/common.py#L202

```
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]: Traceback (most recent call last):
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "/usr/bin/rbd-target-api", line 4, in <module>
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:     __import__('pkg_resources').run_script('ceph-iscsi==3.0', 'rbd-target-api')
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:     self.require(requires)[0].run_script(script_name, ns)
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:     exec(script_code, namespace, namespace)
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "/usr/local/lib/python2.7/dist-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2691, in <module>
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:     
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/common.py", line 87, in __init__
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]:   File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/common.py", line 202, in _upgrade_config
Apr 02 20:49:58 new-croit-host-C0DE01 rbd-target-api[2735]: KeyError: 'controls'
Apr 02 20:49:58 new-croit-host-C0DE01 systemd[1]: rbd-target-api.service: Main proces
```

My gateway.conf is version 3 and doesn't have a 'controls' field.

**Comment by emmericp** [comment]
Looks like this field was introduced here https://github.com/ceph/ceph-iscsi/commit/8ef5452b5edeaf0a49d4687e6f9d8a1954d613f7 without bumping the config version and the upgrade thus fails.

**Comment by ricardoasmarques** [comment]
I've submitted a fix for this issue: https://github.com/ceph/ceph-iscsi/pull/62

**Comment by emmericp** [comment]
thanks for the quick fix - upgrade is now working :)
